### ISSUE TITLE
Player side filter has problem with uppercase characters

### ISSUE THREAD

**Issue by Sur3** [tailuge/mistake-o-tron#28]
If I type my username as _SimonDerZauberer_ (like how it is written in lichess), the mistake-o-tron shows only blacks errors despite me playing white in many of those games. So I have to type my name as all lowercase characters _simonderzauberer_ for mistake-o-tron to show my errors as white as well insted of my enemies errors in those games.

**Comment by tailuge** [comment]
should be fixed now
